name: generate animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: snake-update
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: LinJJ12
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: copy snake svg to assets
        run: |
          mkdir -p assets
          cp dist/github-contribution-grid-snake.svg assets/
          cp dist/github-contribution-grid-snake-dark.svg assets/

      - name: commit snake svg to main branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "更新贪吃蛇贡献动画"
          file_pattern: assets/github-contribution-grid-snake*.svg
